name: mongo-db-test
services:
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    container_name: mongo-test-dev
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    volumes:
      - ./data:/data/db
    networks:
      - back
    restart: unless-stopped

networks:
  back:
    driver: bridge
