name: mongo-test
services:
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    container_name: mongo-ecom-test
    environment:
      - MONGO_INITDB_ROOT_USERNAME={MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD={MONGO_PASS}
    volumes:
      - ./data:/data/db
    networks:
      - back
    restart: unless-stopped

  server:
    build:
      context: ./sv
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file: .env.test_prod
    networks:
      - back
    restart: unless-stopped

networks:
  back:
    driver: bridge
