services:
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    container_name: mongo-ecom
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    volumes:
      - ./data:/data/db
    networks:
      - back
    restart: unless-stopped

  server:
    build:
      context: ./sv
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - PORT=${PORT}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - RUNNING_ENV=${RUNNING_ENV}
      - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
      - PAYPAL_CLIENT_SECRET=${PAYPAL_CLIENT_SECRET}
    networks:
      - back
    restart: unless-stopped

networks:
  back:
    driver: bridge
