services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo-ecom
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    volumes:
      - ./data:/data/db
    networks:
      - back

  server:
    build:
      context: ./sv
    ports:
      - 3000:3000
    depends_on:
      - mongo
    networks:
      - back

networks:
  back:
    driver: bridge
